### ISSUE TITLE
Archive Cleanup

### ISSUE THREAD

**Issue by ardichoke** [echothrust/echofish#68] opened 2017-02-20 15:19 UTC
There are settings that define how long to keep archived logs around, however, it doesn't seem to actually clean up the old data. I'd like to look into this further, but don't see where the cleanup is actually supposed to happen. Where is this supposed to occur (or is it not yet implemented)?

**Comment by gadamo** [comment] 2017-02-21 09:35
@ardichoke That's odd. The functionality is implemented and enabled by default. The settings are described in `/index.php?r=settings/default/help#sysconf` of echofish. 

The functionality exists in the database procedure `eproc_rotate_archive` and fired every 24 hours by the event `e_rotate_archive`. You can find the code for the procedure and the event in `schema/echofish-procedures.sql` and `schema/echofish-events.sql` respectively.

To narrow the issue, please let us know of details relevant to your setup (os/database) and the output from the following SQL statements:

1. Check the min/max timestamps for entries in your archive:
   
   ```
    SELECT MIN(received_ts),MAX(received_ts),NOW() from archive
   ```
2. Make sure that a) mysql's event scheduler is ON and b) the event status is ENABLED:
   
   ```
   SELECT @@EVENT_SCHEDULER;
   SHOW EVENTS WHERE name='e_rotate_archive' \G;
   ```

**Comment by ardichoke** [comment] 2017-02-21 15:05
Everything seems to be fine.... The timestamp query isn't going to be helpful I'm afraid (I manually cleaned up my archive yesterday when I realized that logs weren't being pruned)

```
SELECT MIN(received_ts),MAX(received_ts),NOW() from archive;
+---------------------+---------------------+---------------------+
| MIN(received_ts)    | MAX(received_ts)    | NOW()               |
+---------------------+---------------------+---------------------+
| 2016-12-01 00:00:00 | 2017-02-21 09:56:28 | 2017-02-21 09:56:42 |
+---------------------+---------------------+---------------------+

```

Here's the event scheduling info:
```
MariaDB [logs]> SELECT @@EVENT_SCHEDULER;
+-------------------+
| @@EVENT_SCHEDULER |
+-------------------+
| ON                |
+-------------------+
1 row in set (0.00 sec)

MariaDB [logs]> SHOW EVENTS WHERE name='e_rotate_archive' \G;
*************************** 1. row ***************************
                  Db: logs_ardichoke_info
                Name: e_rotate_archive
             Definer: root@localhost
           Time zone: +00:00
                Type: RECURRING
          Execute at: NULL
      Interval value: 1
      Interval field: DAY
              Starts: 2016-03-08 19:53:23
                Ends: NULL
              Status: ENABLED
          Originator: 1
character_set_client: utf8
collation_connection: utf8_general_ci
  Database Collation: utf8_unicode_ci
1 row in set (0.00 sec)

```

**Comment by gadamo** [comment] 2017-02-22 07:41
@ardichoke Please also provide us with more details on your setup, e.g.:

1. Operating system and version of the host running the database
2. Database server and version (`mysql -V`)
3. The `[mysqld]` section of the database config file `my.cnf`

Feel free to include any other information that you consider relevant or special about your setup.

Knowing that the scheduler is running and the event is ENABLED, let's try to get to the bottom of this by manually testing the procedure to see if any errors/warnings occur:

```
CALL eproc_rotate_archive();
SHOW WARNINGS;
```

For the purpose of testing this sooner: If you don't have old entries in the archive, consider changing the setting `archive_delete_days` (default 7) to a smaller value (e.g. 1).

**Comment by ardichoke** [comment] 2017-02-22 21:24
Sorry about that

Debian 7

mysql  Ver 15.1 Distrib 10.0.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

```
[mysqld]
user            = mysql
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
port            = 3306
basedir         = /usr
datadir         = /var/lib/mysql
tmpdir          = /tmp
lc_messages_dir = /usr/share/mysql
lc_messages     = en_US
skip-external-locking
bind-address            = 127.0.0.1
max_connections         = 100
connect_timeout         = 5
max_allowed_packet      = 16M
thread_cache_size       = 128
sort_buffer_size        = 4M
bulk_insert_buffer_size = 16M
tmp_table_size          = 32M
max_heap_table_size     = 32M
myisam_recover          = BACKUP
key_buffer_size         = 128M
table_open_cache        = 400
myisam_sort_buffer_size = 512M
concurrent_insert       = 2
read_buffer_size        = 2M
read_rnd_buffer_size    = 1M
query_cache_limit               = 512K
query_cache_size                = 64M
log_warnings            = 2
slow_query_log_file     = /var/log/mysql/mariadb-slow.log
long_query_time = 10
log_slow_verbosity      = query_plan

log_bin                 = /var/log/mysql/mariadb-bin
log_bin_index           = /var/log/mysql/mariadb-bin.index
expire_logs_days        = 10
max_binlog_size         = 100M
binlog_format           = 'MIXED'
default_storage_engine  = InnoDB
innodb_buffer_pool_size = 256M
innodb_buffer_pool_instances = 1
innodb_log_buffer_size  = 8M
innodb_file_per_table   = 1
innodb_open_files       = 400
innodb_io_capacity      = 400
innodb_flush_method     = O_DIRECT
innodb_file_format      = Barracuda
event_scheduler = on
```

```
MariaDB [logs]> CALL eproc_rotate_archive();
Query OK, 0 rows affected (26.40 sec)

MariaDB [logs]> SHOW WARNINGS;
Empty set (0.00 sec)

```

**Comment by gadamo** [comment] 2017-02-23 14:27
@ardichoke Looks to me like the procedure works. I believe you will be able to verify it works by following these steps:

1. Acknowledge all/old entries from Syslog
2. If you use Abuser, delete abuser findings too
3. Use `SELECT COUNT(*) from archive;` to get a count
4. Use `SELECT MIN(received_ts),MAX(received_ts),NOW() from archive` to get min/max timestamps
4. Manually run `CALL eproc_rotate_archive();`
5. Repeat steps 3 & 4 to verify

Beware that any messages that have not yet been acknowledged (and therefore still exist on syslog table with the same ID) are not removed from archive table during this process. Same applies for messages that are part of abuser evidence (just in case you use abuser module too), they will not be removed until you clear the abuser findings.

**Comment by ardichoke** [comment] 2017-02-23 18:25
I'm afraid it's still not actually doing anything.

```
MariaDB [logs]> SELECT COUNT(*) from archive;
+----------+
| COUNT(*) |
+----------+
|  2843976 |
+----------+
1 row in set (17.21 sec)

MariaDB [logs]> SELECT MIN(received_ts),MAX(received_ts),NOW() from archive;
+---------------------+---------------------+---------------------+
| MIN(received_ts)    | MAX(received_ts)    | NOW()               |
+---------------------+---------------------+---------------------+
| 2016-12-01 00:02:29 | 2017-02-23 13:17:15 | 2017-02-23 13:17:21 |
+---------------------+---------------------+---------------------+
1 row in set (16.33 sec)

MariaDB [logs]> CALL eproc_rotate_archive();
Query OK, 0 rows affected (0.43 sec)

MariaDB [logs]> CALL eproc_rotate_archive();
Query OK, 0 rows affected (0.29 sec)

MariaDB [logs]> SELECT COUNT(*) from archive;                                                                                                                                                        
+----------+
| COUNT(*) |
+----------+
|  2838069 |
+----------+
1 row in set (16.68 sec)

MariaDB [logs]> SELECT MIN(received_ts),MAX(received_ts),NOW() from archive;                                                                                                                         
+---------------------+---------------------+---------------------+
| MIN(received_ts)    | MAX(received_ts)    | NOW()               |
+---------------------+---------------------+---------------------+
| 2016-12-01 00:02:29 | 2017-02-23 13:19:06 | 2017-02-23 13:18:53 |
+---------------------+---------------------+---------------------+
1 row in set (18.07 sec)
```

**Comment by gadamo** [comment] 2017-02-24 09:14
The COUNT(*) queries show that at least 5907 log entries where removed. Some entries are ignored, leaving the same MIN(received_ts); Please take the following steps to check what kind of entries are retained, and the extent of retention in your setup:

1. Get the number of entries in archive, that were not rotated because their IDs exist on `archive_unparse` table.
```sql
SELECT count(*) FROM archive as t1 LEFT JOIN archive_unparse AS t2 ON t1.id=t2.id WHERE t2.id IS NOT NULL;
```
2. Those not rotated because their IDs exist on `syslog` table.
```sql
SELECT count(*) FROM archive as t1 LEFT JOIN syslog AS t2 ON t1.id=t2.id WHERE t2.id IS NOT NULL;
```
3. Those not rotated because their IDs exist on `abuser_evidence` table.
```sql
SELECT count(*) FROM archive as t1 LEFT JOIN abuser_evidence AS t2 ON t1.id=t2.archive_id WHERE t2.archive_id IS NOT NULL;
```

Please let me know of your results.

**Comment by ardichoke** [comment] 2017-02-24 16:49
Okay, I see what's going on now, the abuser_evidence filter is just making it look like data isn't being cleaned up...

It seems to me like there should be an expiration on abuser evidence (possibly a separate variable from the archive cleanup, in case it is something that people want to keep for a longer duration) after which the evidence and incidents should be removed, allowing for ancient archive data to also be removed, otherwise it will cause data to be retained indefinitely. At some point, abuser evidence becomes useless anyway, as IP allocations change over time, especially when it comes to abusers who are likely to have their services terminated.

**Comment by gadamo** [comment] 2017-02-28 09:31
This is by design; log entries referenced in abuser findings are considered evidence and retained until you choose to remove the findings. This allows you to cherry-pick abusers you 'd like to keep monitoring if they come back (not all IP allocations are dynamic). Because only the offending messages are kept, space consumption should be minimal. Cleaning-up/deleting abusers is then left up to the administrator.

@ardichoke If you think this ought to be implemented somehow better, we would appreciate if you described your use case.

**Comment by ardichoke** [comment] 2017-03-01 18:25
I understand where you're coming from, but I do not believe all (or most) people want to retain that data until it is manually removed. Even if it defaults to never automatically expire, I am of the opinion that adding an auto-expire timeout on abuser evidence that can be turned on if desired is a good idea. Especially since you already have email reports which reset the counters on the abuser incident page to 0 when it reports an IP as an abuser... so, at least in my case, I basically never even look at the page, relying instead on the email to relay that information to me and only checking the page when there is a particularly bad incident (suggesting that my other abuser mitigations have missed something)

**Comment by gadamo** [comment] 2017-03-06 09:36
@ardichoke Checkout the latest master. With merge #74, abuser rotation is introduced.

Trying to get the best of both worlds, three new keys are created in sysconf:
* `abuser_rotate` default: `no`, Enable or disable rotation of abuser evidence and incidents
* `abuser_keep_days` default: `7`, Delete evidence entries older than ...
* `abuser_keep_incident` default: `yes`, During rotation, also delete the incident entries.

Keeping the key `abuser_keep_incident` to `yes`, allows us to keep the IP and First/Last-seen times of abusers, without holding the evidence. Thus, we still keep track if the IP is recurring (only without the evidence), while archive rotation can normally clear those logs (that would otherwise be treated as evidence).

In this merge, `archive_delete_days` is renamed to `archive_keep_days`, which is also more meaningful.

You may wish to test the upgrade path by following the guideline from UPGRADE.md, but using the file schema/updates/v0.5-to-v0.6.sql.

**Comment by gadamo** [comment] 2017-03-09 16:07
Closing this one, as initial issue report (archive not rotating) was already resolved.

@ardichoke Please open a new issue regarding the new abuser rotation feature we added, should you face any issue(s) with it.

**Closed by gadamo** 2017-03-09 16:07 UTC
