### ISSUE TITLE
Create new host ip not possible

### ISSUE THREAD

**Issue by Talorin** [echothrust/echofish#16] opened 2015-02-26 10:31 UTC
I want to create a new host with the ip eg. "123.34.56.789". But it is not possible. The entry will cut at "123.34.56." How must write the ip?

**Comment by gadamo** [comment] 2015-02-26 11:10
Thank you for reporting this, I can confirm it is a bug.
Upon investigation, the form's field expects the ip address in its Long representation (that is 2065840206 for "123.34.56.78"). We will prepare a fix shortly for this.
This bug has remained unnoticed, because we never had to manually create new hosts; when a message from a new host is received, the host's IP is automatically added to the hosts list.
In your example, once echofish receives a message from "123.34.56.78", you should see a new entry in the hosts list. The hosts list is there mostly to allow for mass dns lookups to get fqdn/shortname, but also for housekeeping (deleting old hosts).

**Comment by gadamo** [comment] 2015-02-26 11:35
@Talorin

**Comment by Talorin** [comment] 2015-02-27 07:28
Thank you for the fix. I can write the ip as "123567890" but not as "123.45.67.890". It is the same as before. The entry will cut at "123.45.76."
And can you fix the index.php with "date_default_timezone_set('Europe/Berlin');" or what ever. An "error 500 date() ..." apear without this.

**Comment by gadamo** [comment] 2015-02-27 09:12
Hi there,

Just to clarify the test:

1. Pull the latest changes from the ```master``` branch:

```
cd echofish
git pull
```

2. Browse to ```settings/host/create``` & add a *valid* IPv4 address in dot-decimal notation:

```
123.123.123.123
```

The host now should be added & displayed correctly. 
If still does not work for you, please include your exact input & the output for both of the steps described above.

Note: We had a bug in the code, which is now fixed (and tested on our Dev environment), but in your bug reports, you are referring to invalid IP addresses; In the dot-decimal notation, the IP address consists of a string of decimal numbers (separated by a dot), each number ranging from 0 to 255.

**Comment by gadamo** [comment] 2015-02-27 15:50
As far as the default timezone is concerned, it is commonly set in the php.ini configuration file, which is global for all php applications running on a server. The process of setting this up is described in both our recipe guides for [echofish with syslog-ng on OpenBSD](https://github.com/echothrust/echofish/blob/master/contrib/Echofish-OpenBSD-syslog_ng.md#configure-php-datetimezone) and for [echofish with rsyslog on CentOS Linux](https://github.com/echothrust/echofish/blob/master/contrib/Echofish-CentOS6-rsyslog.md#php-fpm).

If you are facing difficulty in setting it, or you have reason not to set it in your server's global php.ini file, i would suggest that you opened a new issue to address this separately.

**Closed** 2015-03-09 15:22 UTC
Labels: bug
